"""
Creation Record Exporter

Generates a structured, timestamped creation record for a project or session.
Every export always includes the disclaimer — no conditionals, no overrides.

Supported formats:
  - JSON  (default, machine-readable)
  - TXT   (human-readable plain text)

Endpoint: POST /api/creation/export
"""

from __future__ import annotations

import json
import re
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

# ---------------------------------------------------------------------------
# Disclaimer — ALWAYS included, never optional
# ---------------------------------------------------------------------------

DISCLAIMER_TEXT = (
    "This creation record was generated by Mini Assistant and reflects stored timestamps, "
    "version history, and activity logs. It is intended for documentation purposes only and "
    "does not guarantee legal ownership or replace formal copyright protection."
)


# ---------------------------------------------------------------------------
# Export builder
# ---------------------------------------------------------------------------

def build_export(
    project_id:   str,
    project_title: str,
    created_at:   str,
    history:      List[Dict[str, Any]],
    creator_name: Optional[str] = None,
    description:  Optional[str] = None,
    notes:        Optional[str] = None,
    export_format: str = "json",
) -> Dict[str, Any] | str:
    """
    Build a creation record export payload.

    Args:
        project_id:     Unique project/session identifier.
        project_title:  Human-readable project name.
        created_at:     ISO timestamp of project creation.
        history:        List of message/event dicts with role, content, timestamp.
        creator_name:   Optional — provided by user at export time.
        description:    Optional — project description.
        notes:          Optional — free-form notes.
        export_format:  "json" | "txt"

    Returns:
        dict (JSON format) or str (TXT format).
    """
    now = datetime.now(timezone.utc).isoformat()
    export_id = str(uuid.uuid4())[:12]

    # Core creation record
    creation_record = {
        "export_id":     export_id,
        "exported_at":   now,
        "project_id":    project_id,
        "project_title": project_title,
        "created_at":    created_at,
        "total_turns":   len(history),
        "history":       _sanitize_history(history),
    }

    # Optional creator metadata — only included if provided
    creator_metadata: Dict[str, str] = {}
    if creator_name:
        creator_metadata["creator_name"] = creator_name
    if description:
        creator_metadata["description"] = description
    if notes:
        creator_metadata["notes"] = notes

    if export_format == "txt":
        return _render_txt(creation_record, creator_metadata)

    payload: Dict[str, Any] = {
        "creation_record": creation_record,
        "disclaimer":      DISCLAIMER_TEXT,
    }
    if creator_metadata:
        payload["creator_metadata"] = creator_metadata

    return payload


# ---------------------------------------------------------------------------
# Renderers
# ---------------------------------------------------------------------------

def _render_txt(record: Dict[str, Any], creator_meta: Dict[str, str]) -> str:
    lines = [
        "=" * 50,
        "CREATION RECORD — Mini Assistant",
        "=" * 50,
        f"Export ID:     {record['export_id']}",
        f"Exported at:   {record['exported_at']}",
        f"Project:       {record['project_title']}",
        f"Project ID:    {record['project_id']}",
        f"Created at:    {record['created_at']}",
        f"Total turns:   {record['total_turns']}",
        "",
    ]

    if creator_meta:
        lines += [
            "--- Creator Info ---",
        ]
        if "creator_name" in creator_meta:
            lines.append(f"Creator Name:  {creator_meta['creator_name']}")
        if "description" in creator_meta:
            lines.append(f"Description:   {creator_meta['description']}")
        if "notes" in creator_meta:
            lines.append(f"Notes:         {creator_meta['notes']}")
        lines.append("")

    lines += ["--- Activity Log ---", ""]

    for entry in record.get("history", []):
        role      = entry.get("role", "unknown").upper()
        timestamp = entry.get("timestamp", "")
        content   = entry.get("content", "")[:400]   # truncate very long messages
        lines.append(f"[{timestamp}] {role}:")
        lines.append(content)
        lines.append("")

    lines += [
        "",
        "-" * 50,
        "Disclaimer",
        "-" * 50,
        DISCLAIMER_TEXT,
        "",
    ]

    return "\n".join(lines)


def _sanitize_history(history: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Strip internal fields, keep only role / content / timestamp."""
    result = []
    for msg in history:
        clean: Dict[str, Any] = {
            "role":      msg.get("role", "unknown"),
            "content":   _strip_html_code(msg.get("content") or ""),
            "timestamp": msg.get("timestamp", ""),
        }
        # Only include messages that have actual content
        if clean["content"]:
            result.append(clean)
    return result


def _strip_html_code(content: str) -> str:
    """Replace large HTML code blocks with a compact placeholder in the record."""
    content = re.sub(
        r"```html\s*\n[\s\S]+?```",
        "[HTML app code — see exported file]",
        content,
        flags=re.IGNORECASE,
    )
    return content.strip()
