import React from 'react';
import LegalLayout from './LegalLayout';

export default function DmcaPage() {
  return (
    <LegalLayout title="DMCA & Copyright Policy" lastUpdated="March 21, 2026">

      <p>
        Mini Assistant AI ("Company," "we," "us," or "our") respects the intellectual property rights of
        others and expects all users to do the same. This policy explains our procedures for responding to
        notices of alleged copyright infringement under the Digital Millennium Copyright Act ("DMCA"),
        17 U.S.C. § 512, and our broader approach to copyright on the platform.
      </p>

      <h2>1. AI-Generated Content &amp; Copyright — Critical Disclaimer</h2>
      <p>
        Content generated by AI systems involves significant, evolving, and unresolved legal uncertainty
        regarding authorship, ownership, originality, and infringement. By using the Service, you
        acknowledge and irrevocably agree that:
      </p>
      <ul>
        <li>AI outputs are generated probabilistically and <strong>may resemble, reproduce elements of, or be substantially similar to existing third-party content, including copyrighted works</strong>, without any intent or knowledge on our part;</li>
        <li><strong>We make no representation, warranty, or guarantee that any AI-generated output is original, unique, or free from third-party intellectual property claims of any kind;</strong></li>
        <li>The copyright status of AI-generated content is unsettled under United States law and the laws of most other jurisdictions, and may be subject to change based on legislative or judicial developments;</li>
        <li>You assume full legal responsibility for every prompt you submit and for every use you make of AI-generated outputs, including all infringement, misappropriation, and related claims arising from such use;</li>
        <li>Before using AI outputs commercially, publicly, in published works, or in any context where originality or licensing is required, you must independently assess, verify, and if necessary license or clear any third-party rights that may apply;</li>
        <li>We bear no liability for any intellectual property claim — including copyright, trademark, or trade secret — arising from or relating to AI-generated outputs.</li>
      </ul>

      <h2>2. Prohibited Infringing Use</h2>
      <p>
        You may not use the Service to knowingly reproduce, distribute, publicly display, publicly perform,
        or create derivative works from copyrighted material without authorization from the rights holder
        or a valid legal basis under applicable law (including fair use, fair dealing, or a valid license).
        This prohibition applies to all forms of protected content including text, images, music, video,
        software code, and datasets. Repeat infringement will result in permanent account termination.
      </p>

      <h2>3. DMCA Takedown Notice — Requirements</h2>
      <p>
        If you believe that content accessible through or generated via the Service infringes your copyright,
        you may submit a written DMCA takedown notice to our designated Copyright Agent:
      </p>
      <p>
        <strong>Copyright Agent — Mini Assistant AI</strong><br />
        Email: <strong>dmca@miniassistantai.com</strong>
      </p>
      <p>
        To be valid under 17 U.S.C. § 512(c)(3), your notice <strong>must</strong> include all of the
        following:
      </p>
      <ul>
        <li>A physical or electronic signature of the person authorized to act on behalf of the copyright owner;</li>
        <li>Identification of the copyrighted work claimed to have been infringed, or, if multiple works at a single site are covered by a single notification, a representative list of such works;</li>
        <li>Identification of the allegedly infringing material, with information reasonably sufficient to permit us to locate it on the Service;</li>
        <li>Your contact information, including full name, mailing address, telephone number, and email address;</li>
        <li>A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law;</li>
        <li>A statement that the information in the notification is accurate and, under penalty of perjury, that you are authorized to act on behalf of the owner of the exclusive right that is allegedly infringed.</li>
      </ul>
      <p>
        <strong>Incomplete notices will not be processed and will receive no response.</strong> Submitting
        a materially false, misleading, or bad-faith DMCA notice exposes you to liability under 17 U.S.C.
        § 512(f), including damages, costs, and attorneys' fees, and may constitute a violation of our
        Prohibited Uses Policy.
      </p>

      <h2>4. Counter-Notice Procedure</h2>
      <p>
        If you believe content was removed or disabled as a result of a mistaken or misidentified claim,
        you may submit a counter-notice to our Copyright Agent at the address above. A valid counter-notice
        must include:
      </p>
      <ul>
        <li>Your physical or electronic signature;</li>
        <li>Identification of the material that has been removed or disabled and the location where it appeared before removal;</li>
        <li>A statement under penalty of perjury that you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification;</li>
        <li>Your full name, address, and telephone number;</li>
        <li>A statement that you consent to the jurisdiction of the federal district court for the district of New Jersey, and that you will accept service of process from the person who provided the original takedown notice (or their agent).</li>
      </ul>
      <p>
        Upon receipt of a valid counter-notice, we may restore the disputed material within 10–14 business
        days unless the original claimant files a court action to restrain the restoration within that
        period and notifies us accordingly.
      </p>

      <h2>5. Repeat Infringer Policy — Mandatory Termination</h2>
      <p>
        We maintain a strict, mandatory repeat infringer policy in compliance with 17 U.S.C. § 512(i).
        Accounts that are the subject of <strong>two or more valid, non-retracted DMCA takedown
        notices</strong> within any 24-month period will be permanently terminated without warning,
        without refund of any Credits or fees, and without right of appeal. We reserve the right to
        terminate accounts after a single valid notice where circumstances indicate systematic,
        intentional, or commercial-scale infringement. Terminated accounts are permanently banned from
        the Service.
      </p>

      <h2>6. Our Intellectual Property</h2>
      <p>
        All rights, title, and interest in the Mini Assistant AI platform — including its interface,
        branding, codebase, system prompts, documentation, and all related intellectual property — are
        the exclusive property of Mini Assistant AI and its licensors, protected by United States and
        international copyright, trademark, and other intellectual property laws. Unauthorized
        reproduction, modification, distribution, reverse engineering, or exploitation of Mini Assistant
        AI intellectual property is prohibited and will be pursued to the full extent available under law,
        including injunctive relief and damages.
      </p>

      <h2>7. AI Training Data Disclaimer</h2>
      <p>
        The AI models accessible through the Service were developed by third-party providers (including
        Anthropic and OpenAI) and trained on datasets that may include third-party content. We do not
        control the composition, licensing, or provenance of those training datasets and are not
        responsible for any intellectual property implications arising from third-party AI training
        practices. Claims related to AI training data must be directed to the relevant AI provider.
      </p>

      <h2>8. Contact</h2>
      <p>
        DMCA notices and counter-notices: <strong>dmca@miniassistantai.com</strong><br />
        General copyright and IP questions: <strong>legal@miniassistantai.com</strong>
      </p>

    </LegalLayout>
  );
}
