import React from 'react';
import LegalLayout from './LegalLayout';

export default function DmcaPage() {
  return (
    <LegalLayout title="DMCA & Copyright Policy" lastUpdated="March 21, 2026">

      <p>
        Mini Assistant ("Company," "we," "us," or "our") respects the intellectual property rights of others
        and expects all users to do the same. This DMCA &amp; Copyright Policy explains our procedures for
        responding to notices of alleged copyright infringement under the Digital Millennium Copyright Act
        ("DMCA"), 17 U.S.C. § 512, and our general approach to intellectual property on the platform.
      </p>

      <h2>1. AI-Generated Content &amp; Copyright Uncertainty</h2>
      <p>
        Content generated by AI systems involves significant and evolving legal uncertainty regarding
        authorship, ownership, and infringement. You acknowledge and agree that:
      </p>
      <ul>
        <li>AI-generated outputs may resemble, incorporate elements of, or be substantially similar to third-party copyrighted works;</li>
        <li>The copyright status of AI-generated content is unsettled and varies by jurisdiction;</li>
        <li>We make no representation or warranty that AI-generated outputs are free from third-party intellectual property claims;</li>
        <li>You assume full legal responsibility for the prompts you submit and any use you make of AI-generated outputs, including any infringement claims arising from such use;</li>
        <li>Before using AI outputs commercially or publicly, you should independently assess whether such use implicates third-party rights.</li>
      </ul>

      <h2>2. Prohibited Infringing Use</h2>
      <p>
        You may not use the Service to reproduce, distribute, publicly display, publicly perform, or create
        derivative works of copyrighted material without authorization from the rights holder or a valid legal
        basis (e.g., fair use, license). This prohibition applies equally to text, images, music, code, and
        any other protected works. Repeat infringement is grounds for permanent account termination.
      </p>

      <h2>3. DMCA Takedown Procedure — Submitting a Notice</h2>
      <p>
        If you believe that content accessible through or generated via the Service infringes your copyright,
        you may submit a written DMCA takedown notice to our designated Copyright Agent at:
      </p>
      <p>
        <strong>DMCA Agent — Mini Assistant</strong><br />
        Email: <strong>dmca@miniassistantai.com</strong>
      </p>
      <p>
        Your notice must include <strong>all</strong> of the following to be valid under 17 U.S.C. § 512(c)(3):
      </p>
      <ul>
        <li>A physical or electronic signature of the person authorized to act on behalf of the copyright owner;</li>
        <li>Identification of the copyrighted work claimed to have been infringed (or, if multiple works, a representative list);</li>
        <li>Identification of the material claimed to be infringing, with sufficient information to allow us to locate it;</li>
        <li>Your contact information, including name, address, telephone number, and email address;</li>
        <li>A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law;</li>
        <li>A statement that the information in the notice is accurate, and under penalty of perjury, that you are authorized to act on behalf of the copyright owner.</li>
      </ul>
      <p>
        Incomplete or bad-faith notices will not be processed. Submitting a false or materially misleading
        takedown notice exposes you to liability under 17 U.S.C. § 512(f) and may be reported to appropriate
        authorities.
      </p>

      <h2>4. Counter-Notice Procedure</h2>
      <p>
        If you believe content was removed or disabled as a result of a mistaken or misidentified claim, you
        may submit a counter-notice to our Copyright Agent at the address above. A valid counter-notice must
        include:
      </p>
      <ul>
        <li>Your physical or electronic signature;</li>
        <li>Identification of the material that has been removed and the location at which it appeared before removal;</li>
        <li>A statement under penalty of perjury that you have a good faith belief that the material was removed as a result of mistake or misidentification;</li>
        <li>Your name, address, and telephone number;</li>
        <li>A statement that you consent to the jurisdiction of the federal district court in New Jersey, and that you will accept service of process from the party who submitted the original takedown notice.</li>
      </ul>
      <p>
        Upon receipt of a valid counter-notice, we may restore the disputed material within 10–14 business
        days unless the original claimant files a court action within that period.
      </p>

      <h2>5. Repeat Infringer Policy</h2>
      <p>
        We maintain a strict repeat infringer policy. Accounts that are the subject of three or more valid
        DMCA takedown notices within any 12-month period — or that we determine, in our sole discretion, to
        be engaged in systematic infringement — will be permanently terminated without warning, without refund
        of any credits or fees, and without right of appeal. We reserve the right to terminate accounts on
        fewer notices where circumstances warrant.
      </p>

      <h2>6. Our Intellectual Property</h2>
      <p>
        All rights, title, and interest in the Mini Assistant platform — including its interface, branding,
        codebase, system prompts, documentation, and all related intellectual property — are the exclusive
        property of Mini Assistant and its licensors, protected by copyright, trademark, and other intellectual
        property laws. Unauthorized reproduction, modification, distribution, or use of any Mini Assistant
        intellectual property is strictly prohibited and will be pursued to the full extent of the law.
      </p>

      <h2>7. Third-Party IP in AI Training Data</h2>
      <p>
        The AI models accessible through the Service were trained by third-party providers (Anthropic, OpenAI,
        and others) on datasets that may include third-party content. We do not control the composition of those
        training datasets and are not responsible for any intellectual property implications arising from
        third-party AI training practices. Any claims related to AI training data must be directed to the
        respective AI provider.
      </p>

      <h2>8. Contact</h2>
      <p>
        DMCA notices and counter-notices: <strong>dmca@miniassistantai.com</strong><br />
        General copyright questions: <strong>legal@miniassistantai.com</strong>
      </p>

    </LegalLayout>
  );
}
