import React from 'react';
import LegalLayout from './LegalLayout';

export default function DmcaPage() {
  return (
    <LegalLayout title="DMCA & Copyright Policy" lastUpdated="March 2026">
      <h2>Our Commitment</h2>
      <p>Mini Assistant respects intellectual property rights and complies with the Digital Millennium Copyright Act (DMCA). We respond promptly to valid takedown notices.</p>

      <h2>Reporting Copyright Infringement</h2>
      <p>If you believe content on Mini Assistant infringes your copyright, send a DMCA takedown notice to <strong>miniassistantai@gmail.com</strong> with the following information:</p>
      <ul>
        <li>Your name, address, phone number, and email address</li>
        <li>A description of the copyrighted work you claim has been infringed</li>
        <li>A description of where the infringing content is located on our Service</li>
        <li>A statement that you have a good faith belief the use is not authorised by the copyright owner</li>
        <li>A statement that the information in the notice is accurate and, under penalty of perjury, that you are the copyright owner or authorised to act on their behalf</li>
        <li>Your physical or electronic signature</li>
      </ul>

      <h2>Counter-Notice</h2>
      <p>If you believe content was removed incorrectly, you may send a counter-notice to the same email address with:</p>
      <ul>
        <li>Your contact information</li>
        <li>Identification of the removed content and its location before removal</li>
        <li>A statement under penalty of perjury that you have a good faith belief the content was removed by mistake</li>
        <li>Your consent to jurisdiction in the relevant federal district court</li>
        <li>Your signature</li>
      </ul>

      <h2>Repeat Infringers</h2>
      <p>We will terminate accounts of users who are found to be repeat infringers in appropriate circumstances.</p>

      <h2>AI-Generated Content & Copyright</h2>
      <p>Images and content generated by AI are created based on your prompts. We make no warranties about the copyright status of AI-generated output. You are responsible for ensuring your use of AI-generated content complies with applicable law.</p>

      <h2>Contact</h2>
      <p>DMCA notices: <strong>miniassistantai@gmail.com</strong></p>
    </LegalLayout>
  );
}
