import React from 'react';
import LegalLayout from './LegalLayout';

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="March 2026">
      <h2>1. Acceptance of Terms</h2>
      <p>By accessing or using Mini Assistant ("Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>

      <h2>2. Description of Service</h2>
      <p>Mini Assistant is an AI-powered workspace that provides chat, code assistance, app building, and image generation capabilities. The Service is provided on a credit-based subscription model.</p>

      <h2>3. User Accounts</h2>
      <p>You must create an account to use the Service. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must be at least 13 years old to use the Service.</p>

      <h2>4. Credits & Payments</h2>
      <p>The Service operates on a credit system. Credits are consumed when you use AI features. Subscription credits reset monthly; top-up credits never expire. All purchases are final unless otherwise stated in our Refund Policy. We reserve the right to change pricing with 30 days notice.</p>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to use the Service to generate content that is illegal, harmful, deceptive, or violates our Prohibited Items policy. We reserve the right to suspend or terminate accounts that violate these terms without refund.</p>

      <h2>6. AI-Generated Content</h2>
      <p>Content generated by AI is provided as-is. You retain ownership of prompts you submit. AI output may not be accurate, complete, or suitable for all purposes. Do not rely solely on AI output for medical, legal, financial, or safety-critical decisions.</p>

      <h2>7. Intellectual Property</h2>
      <p>The Mini Assistant platform, branding, and underlying technology are our intellectual property. You may not reverse-engineer, copy, or redistribute the platform without written permission.</p>

      <h2>8. Disclaimer of Warranties</h2>
      <p>THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DO NOT GUARANTEE UPTIME, ACCURACY, OR AVAILABILITY OF AI MODELS.</p>

      <h2>9. Limitation of Liability</h2>
      <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICE.</p>

      <h2>10. Changes to Terms</h2>
      <p>We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance. We will notify users of material changes via email or in-app notification.</p>

      <h2>11. Contact</h2>
      <p>For questions about these Terms, contact us at support@miniassistantai.com.</p>
    </LegalLayout>
  );
}
